/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as WidgetRouteImport } from './routes/widget'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as LayoutMonthRouteImport } from './routes/_layout.month'
import { Route as LayoutTasksRouteImport } from './routes/_layout.tasks'
import { Route as LayoutTodayRouteImport } from './routes/_layout.today'
import { Route as LayoutWeekRouteImport } from './routes/_layout.week'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetRoute = WidgetRouteImport.update({
  id: '/widget',
  path: '/widget',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMonthRoute = LayoutMonthRouteImport.update({
  id: '/month',
  path: '/month',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTasksRoute = LayoutTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTodayRoute = LayoutTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWeekRoute = LayoutWeekRouteImport.update({
  id: '/week',
  path: '/week',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/widget': typeof WidgetRoute
  '/month': typeof LayoutMonthRoute
  '/tasks': typeof LayoutTasksRoute
  '/today': typeof LayoutTodayRoute
  '/week': typeof LayoutWeekRoute
}
export interface FileRoutesByTo {
  '/widget': typeof WidgetRoute
  '/month': typeof LayoutMonthRoute
  '/tasks': typeof LayoutTasksRoute
  '/today': typeof LayoutTodayRoute
  '/week': typeof LayoutWeekRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/widget': typeof WidgetRoute
  '/_layout/month': typeof LayoutMonthRoute
  '/_layout/tasks': typeof LayoutTasksRoute
  '/_layout/today': typeof LayoutTodayRoute
  '/_layout/week': typeof LayoutWeekRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/widget' | '/month' | '/tasks' | '/today' | '/week'
  fileRoutesByTo: FileRoutesByTo
  to: '/widget' | '/month' | '/tasks' | '/today' | '/week' | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/widget'
    | '/_layout/month'
    | '/_layout/tasks'
    | '/_layout/today'
    | '/_layout/week'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  WidgetRoute: typeof WidgetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget': {
      id: '/widget'
      path: '/widget'
      fullPath: '/widget'
      preLoaderRoute: typeof WidgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/month': {
      id: '/_layout/month'
      path: '/month'
      fullPath: '/month'
      preLoaderRoute: typeof LayoutMonthRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tasks': {
      id: '/_layout/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof LayoutTasksRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/today': {
      id: '/_layout/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof LayoutTodayRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/week': {
      id: '/_layout/week'
      path: '/week'
      fullPath: '/week'
      preLoaderRoute: typeof LayoutWeekRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutMonthRoute: typeof LayoutMonthRoute
  LayoutTasksRoute: typeof LayoutTasksRoute
  LayoutTodayRoute: typeof LayoutTodayRoute
  LayoutWeekRoute: typeof LayoutWeekRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutMonthRoute: LayoutMonthRoute,
  LayoutTasksRoute: LayoutTasksRoute,
  LayoutTodayRoute: LayoutTodayRoute,
  LayoutWeekRoute: LayoutWeekRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  WidgetRoute: WidgetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
